### ISSUE TITLE
How to install in Sublime Text 4

### ISSUE THREAD

**Issue by Allmedialab** [jfcherng-sublime/ST-BootstrapAutocomplete#1]
Hi,
Thanks for making the plugin! I made you a donation. How do I get the plugin installed in Sublime Text 4?
Regards,
David

**Comment by jfcherng** [comment]
Thanks for the donation :)

The package is on Package Control now.

**Comment by Allmedialab** [comment]
Thanks for the info!

Would it be possible to create some kind of switch to flip from BS4 to BS5? Because I work in Bootstrap 5 now, but some older projects will stay in BS4.  Or can I only change it in the plugin settings?

**Comment by jfcherng** [comment]
> Would it be possible to create some kind of switch to flip from BS4 to BS5? Because I work in Bootstrap 5 now, but some older projects will stay in BS4. Or can I only change it in the plugin settings?

The plugin settings are global but can be override by project settings.

If you are using ST project, you can set the targeted BS version in the project settings as suggested in the README here https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete#project-settings

Project settings can be found from the main menu: `Project` -> `Edit Project...`

---

If you are using ST's project feature yet, I suggest https://packagecontrol.io/packages/ProjectManager.

**Comment by Allmedialab** [comment]
Thanks for the suggestions!

**Comment by jfcherng** [comment]
Just a FYI, this plugin has just been accepted adding into Package Control. So you should be able to install it by the name of `BootstrapAutocomplete` from Package Control, which is the recommended way.

**Comment by y377** [comment]
> Just a FYI, this plugin has just been accepted adding into Package Control. So you should be able to install it by the name of `BootstrapAutocomplete` from Package Control, which is the recommended way.

The version parameter cannot be selected and modified after I install the package. Then follow the following method, successfully installed and used, just you provide url **`404`**, thank you for your plug-in!

> Thanks for the donation :)
> 
> Before this plugin is available on Package Control, which takes time. You can manually install this package by following steps.
> 
> 1. Download plugin source code from https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/archive/refs/heads/main.zip
> 2. Unzip the downloaded `main.zip`
> 3. Rename `ST-BootstrapAutocomplete-main` directory to `BootstrapAutocomplete`
> 4. Open ST, from the main menu: `Preferences...` -> `Browse Packages...`
> 5. Put `BootstrapAutocomplete` directory into the directory which ST just opens
> 6. Maybe restart ST

hi [page 404](https://codeload.github.com/jfcherng-sublime/ST-BootstrapAutocomplete/zip/refs/heads/main)

> https://codeload.github.com/jfcherng-sublime/ST-BootstrapAutocomplete/zip/refs/heads/main

**Comment by jfcherng** [comment]
> The version parameter cannot be selected and modified after I install the package.

You can, just like other plugins. Unless we are talking about you are a ST novice, so you don't know how to modify plugin settings. Otherwise, you have to elaborate further. If you don't know how to elaborate, a screen recording or screenshot is fine. It's read just like "it doesn't work" to me at this moment.

> Before this plugin is available on Package Control, which takes time. You can manually install this package by following steps.

I don't see the reason that why people want to install without Package Control. But whatever, the `main` branch is `st4` now.

**Comment by florescuadrian86** [comment]
![Untitled](https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/assets/39056624/a398b8c4-daa7-483f-903d-95348e72a628)
Can install it in sublime text 4.169??

**Comment by jfcherng** [comment]
> ![Untitled](https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/assets/39056624/a398b8c4-daa7-483f-903d-95348e72a628)
> Can install it in sublime text 4.169??

I can see this plugin in your screenshot. See console to find error messages.

**Comment by florescuadrian86** [comment]
Yes, but when I press TAB button on my keyboard not autocomplete
![Capture](https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/assets/39056624/5af71766-758d-4081-b8d6-4afc40043f99)

**Comment by jfcherng** [comment]
> Yes, but when I press TAB button on my keyboard not autocomplete ![Capture](https://private-user-images.githubusercontent.com/39056624/338562422-5af71766-758d-4081-b8d6-4afc40043f99.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDY4MTksIm5iZiI6MTcxODEwNjUxOSwicGF0aCI6Ii8zOTA1NjYyNC8zMzg1NjI0MjItNWFmNzE3NjYtNzU4ZC00MDgxLWI4ZDYtNGFmYzQwMDQzZjk5LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDExNDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZWIxMzhjNWJlNGQ3NjVkOGI5NjEwMjIwNjE1OWVmZWRiZWJiNmY0MjY0MTgyZWQxYmNjMGQ1NGU0OGI3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.68jx-NCK-36prFbtXRVOBtUwclmy5U5BLDwoki31VEw)

This plugin completes class name just like the screenshot in readme. I don't think your context is legit for completing a class name, but if you insist, you can change https://github.com/jfcherng-sublime/ST-BootstrapAutocomplete/blob/d9f459b2c33d0bc0870b6354ad75f7ba68b075c8/BootstrapAutocomplete.sublime-settings#L3-L6 to whatever context you want. `text.html` will complete class name at everywhere in a HTML-like context.
