### ISSUE TITLE
Cannot disable package for specific projects

### ISSUE THREAD

**Issue by etoundi2nd** [jfcherng-sublime/ST-BootstrapAutocomplete#4]
Disabling the package in a `*.sublime-project` does not have any effect.

example project settings
```js
{
    "folders": [
        {
            "path": "."
        }
    ],
    "settings": {
        "ignored_packages": [
            "BootstrapAutocomplete"
        ]
    }
}
```

Can you please help?

**Comment by jfcherng** [comment]
> Note that only settings in the category [Editor Settings](https://www.sublimetext.com/docs/settings.html#editor-settings) may be controlled by a project.
>
> Editor Settings: These settings affect the behavior and functionality presented when editing text in a file. Examples include the font_face, tab_size and spell_check. These settings are presented in the first section of the default settings file.

That's not how ST works. Not all settings can be overwritten in project settings. See the [docs](https://www.sublimetext.com/docs/projects.html#settings-key).

---

However, if you want to disable this package in a project, you can use empty `"versions"` as an alternative. As for other packages, 🤷 .
